#!/usr/bin/env python3

import os
import subprocess
from datetime import datetime

#print(path)
cmd='/home/phablet/bin/makethumbs'
subprocess.call([cmd], shell=True)

print("Content-type: text/html")
print("")
print("""<html><body>
      <h1>PinePhone</h1>
      <a href="/Pictures">Pictures</a>
<br />
<hr />
<br />
      <a href="/">Root</a>
<br />
<hr />
<p> thumbs re-generated </p>
<br />
<br />
      <a href="/cgi-bin/smallthumbs">smallthumbs</a>
<br />
<hr />
      """
)
timenow = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

print(timenow,"""
</body></html>
"""
)
