#!/usr/bin/env python3

import os
import subprocess
from datetime import datetime

path='/home/phablet/thumbnails'
#print(os.walk(top, topdown=True, onerror=None, followlinks=False))
#print(path)
cmd='/home/phablet/bin/preview'
subprocess.call([cmd], shell=True)

print("Content-type: text/html")
print("")
print("""<html><body>
      <h1>PinePhone</h1>
      <a href="/Pictures">Pictures</a>
<br />
<hr />
<br />
      <a href="/">Root</a>
<br />
<hr />
<br />
<center>
    <img src='/Pictures/preview.jpg' >
<br />
<form action="/cgi-bin/pictest">
    <button type="submit" style="font-size : 20px; width: 100%; height: 50px;">pictest</button>
</form>
<br />
      """
)
timenow = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

print(timenow,"""
</center>
</body></html>
"""
)
