#!/usr/bin/env python3

import os
import subprocess
from datetime import datetime
timenow = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

print("Content-type: text/html")
print("")
print("""<html><body>
<center>
<h1>PinePhone</h1>
<a href="/Pictures">Pictures</a>
<br />
<a href="/">Root</a>
<br />
    <img src='/Pictures/preview.jpg?t="""+timenow+ """' >
    <br />
    <form action="/cgi-bin/pictest">
        <button type="submit" style="font-size : 20px; width: 100%; height: 50px;">pictest</button>
   </form>
   <form action="/cgi-bin/bigpic">
        <button type="submit" style="font-size : 20px; width: 100%; height: 50px;">bigpic</button>
   </form>
   <br />
      """
)
print(timenow,"</center></body></html>")
